#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (C) 2011 ~ `(format-time-string "%Y")` ${1:Deepin, Inc}.
#               2011 ~ `(format-time-string "%Y")` ${2:`(get-git-user-name)`}
# 
# Author:     $2 ${3:<`(get-git-user-email)`>}
# Maintainer: $2 $3
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

$0
